<a href="https://colab.research.google.com/github/DilshodovDilmurod/data_sience/blob/main/array_sotred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
arr = np.random.rand(6)
arr

array([0.96776679, 0.28624787, 0.83580299, 0.10852349, 0.87070524,
       0.8021062 ])

In [ ]:
sorted_arr = np.sort(arr) # arr massivdan nusxa olgan holda tartiblanadi

In [ ]:
sorted_arr

array([0.10852349, 0.28624787, 0.8021062 , 0.83580299, 0.87070524,
       0.96776679])

In [ ]:
arr.sort() # arr massivni tartiblash uchun ishlatiladi

In [ ]:
arr

array([0.10852349, 0.28624787, 0.8021062 , 0.83580299, 0.87070524,
       0.96776679])

In [ ]:
row_arr = -np.sort(-arr)
row_arr  # massivni teskari tartiblash uchun ishlatilladi

array([0.96776679, 0.87070524, 0.83580299, 0.8021062 , 0.28624787,
       0.10852349])

In [ ]:
arr2d = np.random.randn(2, 4)
arr2d

array([[ 0.32144168,  0.83735106, -0.37983675,  0.35016163],
       [ 0.45514863, -0.5312452 ,  1.09356815, -2.41577345]])

In [ ]:
row_srt = np.sort(arr2d, axis=0 )   # arr2d ning xar bir ustun  bo'yicha tartiblangan ko'rinishi
row_srt

array([[ 0.32144168, -0.5312452 , -0.37983675, -2.41577345],
       [ 0.45514863,  0.83735106,  1.09356815,  0.35016163]])

In [ ]:
row_str1 = np.sort(arr2d, axis=1)   # arr2d  har bir qator boyicha tartiblangan korinishi
row_str1

array([[-0.37983675,  0.32144168,  0.35016163,  0.83735106],
       [-2.41577345, -0.5312452 ,  0.45514863,  1.09356815]])

In [ ]:
names = (['Dilmurod', 'Nosir', 'Ilhom', 'Ilhom', 'Temur', 'Elomon'])
ints = ([1, 2, 1, 1, 3, 3, 4, 4, 4, 1, 3])

In [ ]:
 np.unique(names)  # names dagi takrorlanmas elementlar

array(['Dilmurod', 'Elomon', 'Ilhom', 'Nosir', 'Temur'], dtype='<U8')

In [ ]:
names

['Dilmurod', 'Nosir', 'Ilhom', 'Ilhom', 'Temur', 'Elomon']

In [ ]:
set(names) # names dagi takrorlanmas elementlar

{'Dilmurod', 'Elomon', 'Ilhom', 'Nosir', 'Temur'}

In [5]:
arr = np.random.rand(2,4)
arr1 = np.random.randn(2,4)
arr1

array([[ 0.12763427,  0.06684089, -0.21247982,  0.68909363],
       [-1.01401543, -0.28875451, -2.22945544, -0.37083176]])

In [ ]:
arr

array([[0.93581757, 0.4171269 , 0.3571666 , 0.2703855 ],
       [0.73520945, 0.6365505 , 0.94827276, 0.34516456]])

In [3]:
arr2 = np.random.randn(4)
arr2

array([ 0.79265298, -0.33660852,  0.58025418,  0.79311755])

In [6]:
np.in1d(arr1, arr2) # arr2 dagi elementlarni arr1 da mavjudligini tekshirish

array([False, False, False, False, False, False, False, False])

In [7]:
names1 = np.array(['Aziz', 'jurat', 'bobur', 'Abror'])
names2 = np.array(['Jahongir', ' hamid', 'renat', ' Abror'])

In [8]:
np.setdiff1d(names1, names2) # names1 massiv ning names2 massivdagi takrorlanmas qiymatini qaytaradi

array(['Abror', 'Aziz', 'bobur', 'jurat'], dtype='<U5')