<a href="https://colab.research.google.com/github/DilshodovDilmurod/data_sience/blob/main/Fayllar_bn_ishlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.save('data', arr)

In [9]:
arr2 = np.load('data.npy')

In [10]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr1 = np.arange(20)

In [12]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
np.savez('arrays', a= arr,b= arr1)

In [23]:
arrays = np.load('arrays.npz')

In [24]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
np.savez_compressed('arrayarr', a = arr, b = arr1)

In [30]:
array = np.load('arrayarr.npz')

In [31]:
array['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
array['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])